# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 16:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpapertitle', models.CharField(max_length=200, verbose_name='Paper Title')),
                ('ctitle', models.CharField(max_length=100, verbose_name='Conference Title')),
                ('facultyauthorname', models.CharField(blank=True, max_length=200, verbose_name='Author-Faculty')),
                ('ugauthorname', models.CharField(blank=True, max_length=200, verbose_name='Author-UG')),
                ('pgauthorname', models.CharField(blank=True, max_length=200, verbose_name='Author-PG')),
                ('rscholarauthorname', models.CharField(blank=True, max_length=200, verbose_name='Author-ResearchScholar')),
                ('venue', models.CharField(max_length=50, verbose_name='Venue')),
                ('cdatefrom', models.DateField(verbose_name='Conference Date From: ')),
                ('cdateto', models.DateField(verbose_name='Conference Date To: ')),
                ('conferencecategory', models.CharField(choices=[('National', 'National'), ('International', 'International')], default='International', max_length=50, verbose_name='Conference Category')),
                ('presentedby', models.CharField(max_length=50, verbose_name='Presented By')),
                ('bestpaperaward', models.BooleanField()),
                ('refformat', models.TextField(max_length=500, verbose_name='Citation Format')),
            ],
            options={
                'ordering': ['cdatefrom'],
            },
        ),
        migrations.CreateModel(
            name='Externalfundedproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projecttitle', models.CharField(max_length=100, verbose_name='Project Title')),
                ('pi', models.CharField(max_length=100, verbose_name='PI')),
                ('copi', models.CharField(max_length=100, verbose_name='Co-PI')),
                ('fundingagency', models.CharField(max_length=200, verbose_name='Funding Agency')),
                ('duration', models.CharField(max_length=50, verbose_name='Duration')),
                ('sanctioneddate', models.DateField(max_length=50, verbose_name='Sanctioned Date')),
                ('sanctionedamount', models.CharField(max_length=50, verbose_name='Sanctioned Amount')),
                ('fundreleasedon', models.CharField(max_length=100, verbose_name='Fund Released On')),
                ('amountreceived', models.CharField(max_length=100, verbose_name='Amount Received')),
                ('completiondate', models.DateField(verbose_name='Completion Date')),
                ('outcome', models.TextField(max_length=500, verbose_name='Outcome')),
            ],
            options={
                'ordering': ['sanctioneddate'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('empid', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('deptname', models.CharField(max_length=20, verbose_name='Department Name')),
                ('facultyname', models.CharField(max_length=20, verbose_name='Faculty Name')),
                ('username', models.CharField(max_length=20, verbose_name='User Name')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='facultyinternalfundedproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projecttitle', models.CharField(max_length=100, verbose_name='Project Title')),
                ('principalinvestigator', models.CharField(max_length=100, verbose_name='PI')),
                ('copi', models.CharField(max_length=100, verbose_name='Co-PI')),
                ('duration', models.CharField(max_length=50, verbose_name='Duration')),
                ('sanctioneddate', models.DateField(max_length=50, verbose_name='Sanctioned Date')),
                ('sanctionedamount', models.CharField(max_length=50, verbose_name='Sanctioned Amount')),
                ('fundreleasedon', models.CharField(max_length=100, verbose_name='Fund Released On')),
                ('amountreceived', models.CharField(max_length=100, verbose_name='Amount Received')),
                ('completiondate', models.DateField(verbose_name='Completion Date')),
                ('outcome', models.TextField(max_length=500, verbose_name='Outcome')),
                ('empid', models.ManyToManyField(max_length=20, to='researchapp.Faculty', verbose_name='Employee ID')),
            ],
            options={
                'ordering': ['sanctioneddate'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papertitle', models.CharField(default='x', max_length=100, verbose_name='Paper Title')),
                ('jtitle', models.CharField(default='x', max_length=200, verbose_name='Journal Name')),
                ('facultyauthorname', models.CharField(blank=True, max_length=200, verbose_name='Author-Faculty')),
                ('ugauthorname', models.CharField(blank=True, max_length=200, verbose_name='Author-UG')),
                ('pgauthorname', models.CharField(blank=True, max_length=200, verbose_name='Author-PG')),
                ('rscholarauthorname', models.CharField(blank=True, max_length=200, verbose_name='Author-ResearchScholar')),
                ('publishedon', models.DateField(default=datetime.datetime(2017, 9, 4, 16, 38, 51, 555972, tzinfo=utc), verbose_name='Published On')),
                ('pageno', models.CharField(blank=True, max_length=50, verbose_name='Page No')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='Volume')),
                ('issnno', models.CharField(blank=True, max_length=50, verbose_name='ISSN NO')),
                ('sjr', models.CharField(blank=True, max_length=50, verbose_name='SJR')),
                ('snip', models.CharField(blank=True, max_length=50, verbose_name='SNIP')),
                ('sciif', models.CharField(blank=True, max_length=50, verbose_name='SCI-IF')),
                ('refformat', models.TextField(blank=True, max_length=500, verbose_name='Citation Format')),
                ('empid', models.ManyToManyField(max_length=20, to='researchapp.Faculty', verbose_name='Employee ID')),
            ],
        ),
        migrations.CreateModel(
            name='studentinternalfundedproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=200, verbose_name='Student Name')),
                ('projecttitle', models.CharField(max_length=100, verbose_name='Project Title')),
                ('pi', models.CharField(max_length=100, verbose_name='PI')),
                ('copi', models.CharField(max_length=100, verbose_name='Co-PI')),
                ('duration', models.CharField(max_length=50, verbose_name='Duration')),
                ('sanctioneddate', models.DateField(max_length=50, verbose_name='Sanctioned Date')),
                ('sanctionedamount', models.CharField(max_length=50, verbose_name='Sanctioned Amount')),
                ('fundreleasedon', models.CharField(max_length=100, verbose_name='Fund Released On')),
                ('amountreceived', models.CharField(max_length=100, verbose_name='Amount Received')),
                ('completiondate', models.DateField(verbose_name='Completion Date')),
                ('outcome', models.TextField(max_length=500, verbose_name='Outcome')),
                ('empid', models.ManyToManyField(max_length=20, to='researchapp.Faculty', verbose_name='Employee ID')),
            ],
            options={
                'ordering': ['sanctioneddate'],
            },
        ),
        migrations.AddField(
            model_name='externalfundedproject',
            name='empid',
            field=models.ManyToManyField(max_length=20, to='researchapp.Faculty', verbose_name='Employee ID'),
        ),
        migrations.AddField(
            model_name='conference',
            name='empid',
            field=models.ManyToManyField(max_length=20, to='researchapp.Faculty', verbose_name='Employee ID'),
        ),
    ]
