# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-04 16:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='facultyname',
            field=models.CharField(max_length=100, verbose_name='Faculty Name'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='publishedon',
            field=models.DateField(default=datetime.datetime(2017, 9, 4, 16, 46, 45, 482064, tzinfo=utc), verbose_name='Published On'),
        ),
    ]
