# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-07 04:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0004_auto_20170906_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='refformat',
            field=models.TextField(blank=True, max_length=500, verbose_name='Citation Format'),
        ),
        migrations.AlterField(
            model_name='externalfp',
            name='amountreceived',
            field=models.CharField(blank=True, max_length=100, verbose_name='Amount Received'),
        ),
        migrations.AlterField(
            model_name='externalfp',
            name='completiondate',
            field=models.DateField(blank=True, verbose_name='Completion Date'),
        ),
        migrations.AlterField(
            model_name='externalfp',
            name='fundreleasedon',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fund Released On'),
        ),
        migrations.AlterField(
            model_name='externalfp',
            name='outcome',
            field=models.TextField(blank=True, max_length=500, verbose_name='Outcome'),
        ),
        migrations.AlterField(
            model_name='facultyifp',
            name='amountreceived',
            field=models.CharField(blank=True, max_length=100, verbose_name='Amount Received'),
        ),
        migrations.AlterField(
            model_name='facultyifp',
            name='completiondate',
            field=models.DateField(blank=True, verbose_name='Completion Date'),
        ),
        migrations.AlterField(
            model_name='facultyifp',
            name='fundreleasedon',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fund Released On'),
        ),
        migrations.AlterField(
            model_name='facultyifp',
            name='outcome',
            field=models.TextField(blank=True, max_length=500, verbose_name='Outcome'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='publishedon',
            field=models.DateField(default=datetime.datetime(2017, 9, 7, 4, 5, 25, 340092, tzinfo=utc), verbose_name='Published On'),
        ),
        migrations.AlterField(
            model_name='studentifp',
            name='amountreceived',
            field=models.CharField(blank=True, max_length=100, verbose_name='Amount Received'),
        ),
        migrations.AlterField(
            model_name='studentifp',
            name='completiondate',
            field=models.DateField(blank=True, verbose_name='Completion Date'),
        ),
        migrations.AlterField(
            model_name='studentifp',
            name='fundreleasedon',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fund Released On'),
        ),
        migrations.AlterField(
            model_name='studentifp',
            name='outcome',
            field=models.TextField(blank=True, max_length=500, verbose_name='Outcome'),
        ),
    ]
